### ISSUE TITLE
Feature suggestion - Flag Manager

### ISSUE THREAD

**Issue by pixeltester** [masagrator/ReverseNX-Tool#2]
I would like to suggest a feature that scans the SaltySD plugins folder and shows the following information below the options in titleid mode:

Game name - titleid - current flag set

Edit - or another idea with a different approach: sys-clk editor style- read installed games and create flags in SaltySD plugins folder inside of ReverseNX tool instead of using next launch. However that could be overcomplicating things for this tool because it's not typical to set a lot of ReverseNX flags.

**Comment by masagrator** [comment]
Why should I show game name and titleid? You don't know what game are you running? :P For this stuff you have other tools. And ReverseNX-Tool already shows used flag for running game in titleid mode for some time.

And another idea is not something bad, just it will not be added any time soon, I want to upload Status Monitor 0.5 and stop adding new features for some time to finish some games.

**Comment by pixeltester** [comment]
> Why should I show game name and titleid? You don't know what game are you running? :P For this stuff you have other tools. And ReverseNX-Tool already shows used flag for running game in titleid mode for some time.

For the first idea you misunderstood what I was suggesting. My suggestion was to scan the SaltyNX folder and show a list of flags that we have already set, not just for the currently running game.

**Comment by masagrator** [comment]
https://github.com/masagrator/ReverseNX-Tool/releases/tag/2.0.0
