### ISSUE TITLE
Doesn't work with Borderland Pre-Sequel

### ISSUE THREAD

**Issue by haywire27** [masagrator/ReverseNX-Tool#8]
Hi there!

Just beat Borderlands 2 and moved on the the Pre-sequel (v1.0.1) but it seems forced handheld does not work with ReverseNX when docked.

It works beautifully with Borderlands 2 btw, just not sure why it's not downscaling to 720p for the pre-sequel game in docked mode.  Am trying to downscale so I can run unlocked FPS to ~60fps

Am running SaltyNX-Tool 1.1.0 as well

Thanks in advance

**Comment by masagrator** [comment]
This was fixed some time ago, so closing.
